ITCompanyTaskManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("task_manager_app.urls", namespace="taskmanager")),
]

taskmanagerApp/urls.py
from django.urls import path

from taskmanagerApp.views import PositionListView, WorkerListView, WorkerDetailView, TaskDetailView, \
    RegisterView, WorkerDeleteView, ProjectListView, ProjectCreateView, ProjectDeleteView, ProjectDetailView, \
    ProjectUpdateView, ProjectTeamsView, TeamUpdateView, TeamCreateView, remove_team_from_project, TaskCreateView, \
    TaskUpdateView, TaskAssignView, TaskDeleteView, IndexView, mark_task_completed, TaskListView, WorkerUpdateView, \
    TeamDeleteView

urlpatterns = [
    path("", IndexView.as_view(), name='index'),
    path("register/", RegisterView.as_view(), name="register"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tasks/<int:pk>/assign/", TaskAssignView.as_view(), name="task-assign"),
    path("tasks/<int:pk>/complete/", mark_task_completed, name="task-complete"),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/<int:pk>/update", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("projects/create/", ProjectCreateView.as_view(), name="project-create"),
    path("projects/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"),
    path("projects/<int:pk>/update/", ProjectUpdateView.as_view(), name="project-update"),
    path("projects/<int:pk>/teams/", ProjectTeamsView.as_view(), name="project-teams"),
    path("teams/<int:pk>/update/", TeamUpdateView.as_view(), name="team-update"),
    path("teams/<int:pk>/delete/", TeamDeleteView.as_view(), name="team-delete"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("projects/<int:project_id>/teams/<int:team_id>/remove/", remove_team_from_project,
         name="remove-team-from-project"),

]
app_name = "taskManagerApp"

task_manager_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

PRIORITY_CHOICES = (
    ("CRITICAL", "Critical"),
    ("ESSENTIAL", "Essential"),
    ("HIGH_PRIORITY", "High Priority"),
    ("MEDIUM_PRIORITY", "Medium Priority"),
    ("LOW_PRIORITY", "Low Priority"),
)


class Position(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position, on_delete=models.CASCADE, related_name="workers"
    )

    class Meta:
        verbose_name = "driver"
        verbose_name_plural = "drivers"

    def __str__(self):
        return f"{self.username} ({self.position.name})"


class TaskType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=100, choices=PRIORITY_CHOICES)
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(Worker, related_name="assigned_tasks")
    project = models.ForeignKey(
        "Project", on_delete=models.CASCADE, related_name="tasks"
    )

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=100, unique=True)
    leader = models.ForeignKey(
        Worker, on_delete=models.SET_NULL, null=True, related_name="led_teams"
    )
    members = models.ManyToManyField(Worker, related_name="teams")

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    deadline = models.DateTimeField()
    priority = models.CharField(max_length=100, choices=PRIORITY_CHOICES)
    teams = models.ManyToManyField(Team, related_name="projects")
    created_at = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

templates/includes/detail-card-styles.html
  <style>
      .detail-card {
          background: #f8f9fa;
          border-radius: 10px;
          padding: 20px;
          box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      }

      .detail-info {
          font-size: 1.1rem;
      }
  </style>

templates/includes/list_styles.html
<style>
    .table-hover tbody tr:hover {
        background-color: palegreen;
        transition: background-color 0.3s ease;
    }
</style>

templates/includes/navigation.html
<header class="navbar pcoded-header navbar-expand-lg navbar-light headerpos-fixed header-blue">
  <div class="m-header d-flex align-items-center gap-3">
    
    <a class="mobile-menu" id="mobile-collapse" href="#">
      <i class="feather icon-menu" style="font-size: 22px;"></i>
    </a>
    
    <a href="{% url 'taskmanager:index' %}" class="b-brand d-flex align-items-center">
      <img src="/static/assets/images/projectary-logo-cropped.png" alt="Logo"
           style="height: 51px; object-fit: contain;">
    </a>

  </div>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav me-auto"></ul>
    <ul class="navbar-nav ms-auto"></ul>
  </div>
</header>

templates/includes/priority-buttons.html
<span class="badge 
    {% if object.priority == 'CRITICAL' %} bg-danger
    {% elif object.priority == 'ESSENTIAL' %} bg-warning
    {% elif object.priority == 'HIGH_PRIORITY' %} bg-primary
    {% elif object.priority == 'MEDIUM_PRIORITY' %} bg-info
    {% else %} bg-secondary {% endif %} task-badge">
    {{ object.get_priority_display }}
</span>

templates/includes/scripts.html
<script src="/static/assets/js/plugins/popper.min.js"></script>
<script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
<script src="/static/assets/js/plugins/bootstrap.min.js"></script>
<script src="/static/assets/js/pcoded.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

<script>
  window.addEventListener("load", function () {
    const loader = document.querySelector(".loader-bg");
    if (loader) {
      loader.style.display = "none";
    }
  });
</script>


    

templates/includes/sidebar.html
<!-- [ navigation menu ] start -->
<nav class="pcoded-navbar menupos-fixed menu-light ">
  <div
      class="navbar-wrapper  ">
    <div class="navbar-content scroll-div "
    >
      <ul class="nav pcoded-inner-navbar ">
        <li class="nav-item">
          <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
              class="pcoded-mtext">Home</span></a>
        </li>
        <li class="nav-item">
          <a href="{% url "taskManagerApp:project-list" %}" class="nav-link "><span class="pcoded-micon"><i
              class="feather icon-folder"></i></span><span class="pcoded-mtext">Projects</span></a>
        </li>
        <li class="nav-item">
          <a href="{% url "taskManagerApp:position-list" %}" class="nav-link "><span class="pcoded-micon"><i
              class="feather icon-box"></i></span><span class="pcoded-mtext">Position List</span></a>
        </li>
        <li class="nav-item">
          <a href="{% url "taskManagerApp:task-list" %}" class="nav-link "><span class="pcoded-micon"><i
              class="feather icon-check-square"></i></span><span class="pcoded-mtext">Task List</span></a>
        </li>
        <li class="nav-item">
          <a href="{% url "taskmanager:worker-list" %}" class="nav-link "><span class="pcoded-micon"><i
              class="feather icon-users"></i></span><span class="pcoded-mtext">Workers</span></a>
        </li>
        <li class="nav-item">
          <a href="{% url 'taskManagerApp:team-create' %}" class="nav-link ">
            <span class="pcoded-micon"><i class="feather icon-user-plus"></i></span>
            <span class="pcoded-mtext">Create a Team</span>
          </a>
        </li>
        <li class="nav-item pcoded-hasmenu">
          <a href="#" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span
              class="pcoded-mtext">Authentication</span></a>
          <ul class="pcoded-submenu">
            <li class="nav-item">
              <form method="post" action="{% url 'logout' %}" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="nav-link w-100 text-left border-0">
                  <i class="feather icon-log-out"></i> Logout
                </button>
              </form>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
              <a id="delete-account" href="{% url 'taskManagerApp:worker-delete' pk=request.user.id %}">
                <i class="feather icon-trash-2"></i> Delete account
              </a>
            {% endif %}
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>

  {% block stylesheets %}
    <style>

        #delete-account::before {
            content: none !important;
        }

        #delete-account:hover {
            color: red;
            text-decoration: underline;
            transition: 0.3s;
        }
    </style>
  {% endblock %}

</nav>

    